---
- hosts: all
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
      become: yes

    - name: Install R
      yum:
        name: R
        state: present
      become: yes

    - name: Install RStudio
      yum: name=https://download2.rstudio.org/rstudio-server-rhel-1.1.453-x86_64.rpm
      become: yes

    - name: Create folder for R libraries
      file: path=/tmp/data/Rpackages state=directory

- hosts: all
  user: root
  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("test", "$1$SomeSalt$")'
    password: $1$SomeSalt$aIJ0bvHJBSYd307VQuuD90

  tasks:
    - name: Create test user
      user: name=test password={{password}}
      become: yes
