---
- hosts: all
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
      become: yes

    - name: Install R
      yum:
        name: R
        state: present
      become: yes

    - name: Install RStudio
      yum: name=https://download2.rstudio.org/rstudio-server-rhel-1.1.453-x86_64.rpm
      become: yes

- hosts: all
  user: root
  vars:
    created with:
    python -c 'import crypt; print crypt.crypt("test", "$1$SomeSalt$")'
    password: $1$SomeSalt$UqddPX3r4kH3UL5jq5/ZI.

  tasks:
    - user: name=test password={{password}}
