---
- hosts: all
  tasks:
    - name: Copy files for testing R
      copy:
        src: /home/centos/aws-consul-terraform/modules/build-r-env/resources/test
        dest: /tmp

    - name: Execute R script
      command:  Rscript /tmp/test/machine_learning_classification_models.R
