---
- hosts: all
  tasks:
    - name: install Jinja2 or force upgrade
      pip:
        name: Jinja2
        state: latest
        extra_args: --user
    - name: install setuptools
      pip:
        name: setuptools
        state: latest
        extra_args: --upgrade
